version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - 3010:3010
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/server

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/client
