version: "2.1"

orbs:
  cypress: cypress-io/cypress@3.4.0

node-image: &node-image cimg/node:18.17.0

parameters:
  client:
    type: boolean
    default: false
  server:
    type: boolean
    default: false

jobs:
  lint-build-client:
    docker:
      - image: *node-image
    working_directory: ~/challenge/client
    steps:
      - checkout:
          path: ~/challenge
      - setup_remote_docker
      - run:
          name: lint test and build
          command: |
            # Install dependencies
            echo "Installing dependencies"
            yarn install
            # Lint
            echo "Linting"
            yarn lint
            # Build client
            echo "Building client"
            yarn build
            # Build and Publish Docker Image
            echo "Building and publishing image"
            docker build -t client . && echo "Image built and published"

  # deploy-client:

  lint-test-build-server:
    docker:
      - image: *node-image
    working_directory: ~/challenge/server
    steps:
      - checkout:
          path: ~/challenge
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: lint test and build
          command: |
            # Install dependencies
            echo "Installing dependencies"
            yarn install
            # Lint
            echo "Linting"
            yarn lint
            # Install JUnit coverage reporter and Run tests
            echo "Running tests"
            yarn add --dev jest-junit
            # Run tests
            yarn test:ci
            # Build server
            echo "Building server"
            yarn build
            # Build and Publish Docker Image
            echo "Building and publishing image"
            docker build -t server . && echo "Image built and published"
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/

  # deploy-server:

workflows:
  build-test-deploy-client:
    # when: << pipeline.parameters.client >>
    jobs:
      - cypress/run:
          name: Run Cypress tests
          package-manager: yarn
          working-directory: ./client
          start-command: yarn dev
          cypress-command: "npx cypress run --component"
          node-version: 18.17.0
      - lint-build-client
      # - deploy-client:
      #     requires:
      #       - lint-test-build-client
  # build-test-deploy-server:
  #   # when: << pipeline.parameters.server >>
  #   jobs:
  #     - lint-test-build-server
  #     # - deploy-server:
  #     #     requires:
  #     #       - lint-test-build-server
# version: '2.1'

# setup: true

# orbs:
#   path-filtering: circleci/path-filtering@1.1.0

# workflows:
#   generate-config:
#     jobs:
#       - path-filtering/filter:
#           mapping: client/* client true server/* server true
#           config-path: .circleci/continue_config.yml
#           filters:
#             branches:
#               only: main

